import os
from datetime import date, timedelta
from typing import Dict
import pandas as pd
from oil_optimization.utils.io_helpers import read_yaml

def load_dataframes() -> Dict[str,pd.DataFrame]:
    """
    Defines a dictionary that will contain all
    data extracted from the APIs
    """

    config = read_yaml('config/config.yml')
    data_dir = config['data_ingestion']['root_dir']
    raw_data_dir = data_dir + '/raw'
    file_list = os.listdir(raw_data_dir)

    dataframes = {}
    for filename in file_list:
        key = filename[:-4] #Removing .csv extension from filename
        try:
            dataframes[key] = pd.read_csv(f'{raw_data_dir}/{filename}', parse_dates=['period'])
        except FileNotFoundError as e:
            print(e)

    return dataframes

def create_base_dataframe() -> pd.DataFrame:
    """
    Creates a DataFrame to build the features with keys to merge
    data in correct time intervals.
    """
    features_df = pd.DataFrame()
    today = date.today().strftime('%Y-%m-%d')

    #Setting a weekly index starting from 2015-01-02
    features_df['period'] =  pd.date_range(start='2015-01-02',
                                        end=today,
                                        freq='W') - timedelta(days=2)
    #Setting key to merge with monthly data
    features_df['year_month'] = features_df['period'].dt.strftime('%Y-%m')

    return features_df

def monthly_merge(main_df: pd.DataFrame,
                  feature_df: pd.DataFrame,
                  out_label: str | None = None
                  ) -> pd.DataFrame:
    """
    Merge between main dataframe with timestamp keys
    and dataframe that contains the feature to be appended

    Args:
    main_df: 
        Main dataframe with all features
    feature_df:
        Dataframe that contains the feature that will be added to main_df
    out_label (optional):
        If passed, label name that will have the added feature in the
        the resulting dataframe

    Returns:
        pd.Dataframe: Dataframe with the appended feature from feature_df
    """
    feature_df_filter = feature_df.loc[:,['period','value']] # Filtering relevant data
    feature_df_filter['year_month'] = feature_df_filter['period'].dt.strftime('%Y-%m')

    periods_df = main_df.groupby('year_month').first().reset_index() # Getting keys
    merge_feature = periods_df.merge(feature_df_filter,
                                     on='year_month',
                                     how='left',
                                     suffixes=('','_y'))

    out_df = main_df.merge(merge_feature,
                           on='period',
                           how='left',
                           suffixes=('','_y'))

    #Getting duplicate columns generated by joins
    remove_cols = [col for col in out_df.columns if col.endswith('_y')]
    out_df = out_df.drop(remove_cols,axis=1)

    if out_label:
        out_df.rename({'value':out_label},
                             axis=1,
                             inplace=True)

    return out_df
