import os
from functools import wraps
from datetime import timedelta
from typing import Dict
import pandas as pd
from oil_optimization.utils.io_helpers import read_yaml

def load_dataframes() -> Dict[str,pd.DataFrame]:
    """
    Defines a dictionary that will contain all
    files extracted from the APIs as pandas dataframes
    """

    config = read_yaml('config/config.yml')
    data_dir = config['data_ingestion']['root_dir']
    raw_data_dir = data_dir + '/raw'
    file_list = os.listdir(raw_data_dir)

    dataframes = {}
    for filename in file_list:
        key = filename[:-4] #Removing .csv extension from filename
        try:
            dataframes[key] = pd.read_csv(f'{raw_data_dir}/{filename}', parse_dates=['period'])
        except FileNotFoundError as e:
            print(e)

    return dataframes

def merge_dataframe(processing_func):
    """
    Decorator to add merge functionality after each call to a processing function
    """
    @wraps(processing_func)
    def wrapper(main_df: pd.DataFrame, 
                feature_df: pd.DataFrame,
                out_label: str | None = None
                ) -> pd.DataFrame:

        if processing_func.__name__ == 'monthly_merge':
            processed_df = processing_func(main_df, feature_df)
        else:
            processed_df = processing_func(feature_df)

        out_df = main_df.merge(processed_df,
                           on='period',
                           how='left',
                           suffixes=('','_y'))
        if out_label:
            out_df.rename({'value':out_label}, axis=1, inplace=True)

        # Getting duplicate columns generated by joins
        remove_cols = [col for col in out_df.columns if col.endswith('_y')]
        if remove_cols:
            out_df = out_df.drop(remove_cols,axis=1)

        return out_df

    return wrapper

def process_gasoline(gasoline_df: pd.DataFrame) -> pd.DataFrame:
    """
    Processor for gasoline

    Parameters
    ----------
    gasoline_df: pd.DataFrame
        Dataframe containing gasoline pricing

    Returns
    -------
    pd.DataFrame
    """

    gasoline_df_agg = gasoline_df.groupby('period')['value'].mean().reset_index()

    gasoline_df_agg['period'] = gasoline_df_agg['period'] - timedelta(3)

    return gasoline_df_agg

def process_production(prod_df: pd.DataFrame) -> pd.DataFrame:
    """
    
    """
    prod_df_filter = prod_df[prod_df['units'] == 'MBBL']
    df_prod_sum = prod_df_filter.groupby('period')['value'].sum().reset_index()

    df_prod_sum['year_month'] = df_prod_sum['period'].dt.strftime('%Y-%m')

    return df_prod_sum

@merge_dataframe
def process_imports_exports(feature_df: pd.DataFrame) -> pd.DataFrame:
    """
    
    """
    cols = ['period','process-name','value']
    feature_df = feature_df[cols]
    feature_df = feature_df[feature_df['process-name'].isin(['Imports','Exports'])]

    feature_df = feature_df.pivot(columns=['process-name'],values='value',index='period')

    return feature_df

@merge_dataframe
def process_input_utilization(feature_df: pd.DataFrame) -> pd.DataFrame:
    """
    
    """
    df_input_sorted = feature_df.sort_values(by=['period','area-name'])
    df_input = df_input_sorted.pivot(index='period',columns='area-name',values='value')
    df_input.columns = ['East Coast (PADD 1)',
                                'Midwest (PADD 2)',
                                'Gulf Coast (PADD 3)',
                                'Rocky Mountain (PADD 4)',
                                'West Coast (PADD 5)']

    return df_input

@merge_dataframe
def process_index(feature_df: pd.DataFrame,
                  fill_na: bool = True) -> pd.DataFrame:
    """
    Notes: Volatility_index and us_dollar_index has the same preprocessing
    """
    df_didx = feature_df.copy()
    df_didx = df_didx[['period','value']]
    if fill_na:
        df_didx['value'] = df_didx['value'].replace('.',None).astype(float).interpolate()

    df_didx['value'] = df_didx['value'].rolling(window=5).mean().round(5)

    return df_didx

@merge_dataframe
def monthly_merge(main_df: pd.DataFrame,
                  feature_df: pd.DataFrame
                  ) -> pd.DataFrame:
    """
    Merge between main dataframe with timestamp keys
    and dataframe that contains the feature to be appended

    Args:
        main_df (pd.DataFrame) 
            Main dataframe with all features
        feature_df (pd.DataFrame):
            Dataframe that contains the feature that will be added to main_df

    Returns:
        pd.Dataframe: Dataframe with the appended feature from feature_df
    """
    main_df_copy = main_df.copy()
    periods_df = main_df_copy.groupby('year_month').first().reset_index() # Getting keys

    feature_df_filter = feature_df.loc[:,['period','value']] # Filtering relevant data
    feature_df_filter['year_month'] = feature_df_filter['period'].dt.strftime('%Y-%m')

    merge_feature = periods_df.merge(feature_df_filter,
                                    on='year_month',
                                    how='left',
                                    suffixes=('','_y'))

    return merge_feature
